name: tg-parser-bot
platform: docker

build:
  dockerfile: Dockerfile


run:
  containerPort: 8080
  servicePort: 80

deploy:
  instances: 1
  resources:
    memory: 512
    cpu: 500

services:
  - name: web
    port: 8080
    protocol: http
    healthcheck:
      path: /health
      interval: 30s   
      timeout: 10s
      initial_delay: 30s

env:
  - name: SERVER_HOST
    value: "0.0.0.0"
  - name: SERVER_PORT    
    value: "8080"
  - name: LOG_LEVEL
    value: "info"
  - name: LOG_FORMAT
    value: "json"

volumes:
  - name: session-data
    path: /app