version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tg-parser-db
    environment:
      POSTGRES_DB: tgparser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: