database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "tg_parser_bot"
  ssl_mode: "disable"

telegram:
  api_id: 1234567
  api_hash: "your_api_hash_here"
  phone: "+1234567890"
  session_file: "tg_session"
  bot_token: "your_bot_token_here"
  target_channel: "@your_channel"

vk:
  access_token: "your_vk_access_token"
  group_id: 123456789
  version: "5.131"

server:
  host: "localhost"
  port: 8080

logger:
  level: "info"
  format: "json"
  file_path: "logs/app.log"

auth:
  jwt_secret: "your-super-secret-jwt-key-change-in-production"
  jwt_duration: 24